In [10]:
import argparse
args = argparse.Namespace()
args.dataset="movie"


In [11]:
import numpy as np
import collections
import os


In [12]:
def dataset_split(rating_np):
    print('splitting dataset ...')

    # train:eval:test = 6:2:2
    eval_ratio = 0.2
    test_ratio = 0.2
    n_ratings = rating_np.shape[0]

    eval_indices = np.random.choice(n_ratings, size=int(n_ratings * eval_ratio), replace=False)
    left = set(range(n_ratings)) - set(eval_indices)
    test_indices = np.random.choice(list(left), size=int(n_ratings * test_ratio), replace=False)
    train_indices = list(left - set(test_indices))
    # print(len(train_indices), len(eval_indices), len(test_indices))

    # traverse training data, only keeping the users with positive ratings
    user_history_dict = dict()
    for i in train_indices:
        user = rating_np[i][0]
        item = rating_np[i][1]
        rating = rating_np[i][2]
        if rating == 1:
            if user not in user_history_dict:
                user_history_dict[user] = []
            user_history_dict[user].append(item)

    train_indices = [i for i in train_indices if rating_np[i][0] in user_history_dict]
    eval_indices = [i for i in eval_indices if rating_np[i][0] in user_history_dict]
    test_indices = [i for i in test_indices if rating_np[i][0] in user_history_dict]
    # print(len(train_indices), len(eval_indices), len(test_indices))

    train_data = rating_np[train_indices]
    eval_data = rating_np[eval_indices]
    test_data = rating_np[test_indices]

    return train_data, eval_data, test_data, user_history_dict


In [13]:
def load_rating(args):
    print('reading rating file ...')

    # reading rating file
    rating_file = './data/' + args.dataset + '/ratings_final'
    if os.path.exists(rating_file + '.npy'):
        rating_np = np.load(rating_file + '.npy')
    else:
        rating_np = np.loadtxt(rating_file + '.txt', dtype=np.int32)
        np.save(rating_file + '.npy', rating_np)

    # n_user = len(set(rating_np[:, 0]))
    # n_item = len(set(rating_np[:, 1]))
    print(rating_np)
    return dataset_split(rating_np)

    

In [14]:
load_rating(args)

reading rating file ...
[[   0    0    1]
 [   0 1669    1]
 [   0 1419    1]
 ...
 [6035  861    0]
 [6035  943    0]
 [6035 1798    0]]
splitting dataset ...


(array([[   0, 1932,    1],
        [   0, 1179,    1],
        [   0, 1691,    1],
        ...,
        [6035,  129,    0],
        [6035,  983,    0],
        [6035,  861,    0]], dtype=int32),
 array([[3100, 2252,    0],
        [5827,  146,    0],
        [3226,  189,    1],
        ...,
        [3679,  540,    0],
        [1131,  775,    1],
        [5267,   31,    1]], dtype=int32),
 array([[2545, 1900,    0],
        [ 446,  315,    0],
        [4825,  930,    1],
        ...,
        [5267, 1220,    0],
        [5758, 1853,    0],
        [4113,    1,    1]], dtype=int32),
 {0: [1932,
   1179,
   1691,
   1696,
   2082,
   165,
   939,
   1093,
   1225,
   341,
   1624,
   91,
   1883,
   1760],
  1: [768,
   1417,
   1169,
   1554,
   1175,
   669,
   930,
   2087,
   1833,
   938,
   1451,
   1327,
   309,
   1974,
   1207,
   574,
   2114,
   1091,
   837,
   2124,
   2125,
   206,
   975,
   1361,
   1875,
   1883,
   733,
   737,
   226,
   740,
   231,
   745,
   748,
   